name: Translate README to English

on:
  pull_request:
    paths:
      - 'README.md'
    types: [opened, synchronize]

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do código do repositório
      - name: Checkout the repository
        uses: actions/checkout@v3

      # Configura o ambiente Python para rodar o script de tradução
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Extrai o diff das mudanças feitas no arquivo README.md
      - name: Get changes from README.md
        id: readme_diff
        run: |
          # Faz o fetch da base do PR
          git fetch origin ${{ github.event.pull_request.base.ref }}:base
          # Extrai o diff apenas do arquivo README.md
          git diff base...${{ github.event.pull_request.head.sha }} -- README.md > readme_diff.txt

          # Verifica se há alterações no README.md
          if [ -s readme_diff.txt ]; then
            echo "README.md has been modified."
          else:
            echo "No changes detected in README.md"
            exit 0
          fi

      # Executa o script Python para traduzir o conteúdo modificado
      - name: Run translation script
        run: |
          languages=("en" "es" "fr" "de")

          # Loop sobre a lista e executar o script para cada item
          for lang in "${languages[@]}"; do
            echo "Rodando script para $item"
            python3 scripts/translate.py readme_diff.txt "${lang}"
          done




      # Commit e push das alterações, apenas se o repositório permitir
      - name: Commit and push changes
        if: github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add \*.md
          git commit -m "Updated README.eng.md with translations"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
